// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtPi3TDrn9mHk6r-VVpWea24ksIhdlSHw',
    appId: '1:108856192288:web:a594788cfc6203111c7b45',
    messagingSenderId: '108856192288',
    projectId: 'zoom-app-clone-1fc96',
    authDomain: 'zoom-app-clone-1fc96.firebaseapp.com',
    storageBucket: 'zoom-app-clone-1fc96.appspot.com',
    measurementId: 'G-ZRN5JG2SW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTrQvc-3Aze2ADDMlHpHtYyXArqKS6pds',
    appId: '1:108856192288:android:818c1bd87bd074411c7b45',
    messagingSenderId: '108856192288',
    projectId: 'zoom-app-clone-1fc96',
    storageBucket: 'zoom-app-clone-1fc96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmzxOo-8JisYfgVQG9IajLAxz11Rs4G68',
    appId: '1:108856192288:ios:170daec29800227c1c7b45',
    messagingSenderId: '108856192288',
    projectId: 'zoom-app-clone-1fc96',
    storageBucket: 'zoom-app-clone-1fc96.appspot.com',
    iosClientId: '108856192288-5nkko2f45j45ohvgiir0dlnlh235mbqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmzxOo-8JisYfgVQG9IajLAxz11Rs4G68',
    appId: '1:108856192288:ios:68e5078a19e92f8d1c7b45',
    messagingSenderId: '108856192288',
    projectId: 'zoom-app-clone-1fc96',
    storageBucket: 'zoom-app-clone-1fc96.appspot.com',
    iosClientId: '108856192288-67jjemakhlkqefoq8s6trnrs33ocj54k.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomAppClone.RunnerTests',
  );
}
